title: 小哲的导航网站
avatar: https://pic1.imgdb.cn/item/68955b1758cb8da5c810dc12.jpg
subTitle: 收录学习过程中的优质网站，项目，插件等

# 网站路径
baseURL: '/'

menu:
    - name: 首页
      path: index

# 每一页数量
pageNumber: 30

# 关于网站SEO
SEO:
    author: 小哲
    keywords: 网站，插件，软件，项目
    description: 收集优质网站，项目，插件等
